---
#
# Installs a clean dev environment. Hostnames, bride, some utils
#
- name: Include vars
  hosts: localhost
  tasks:
  - include_vars: vars/global_vars.yml

- hosts: localhost
  remote_user: vagrant
  serial: 1
  roles:
    - common