---
#
# Installs the ONOS tutorials
#
- name: Include vars
  hosts: localhost
  tasks:
  - include_vars: vars/global_vars.yml

- hosts: localhost
  remote_user: vagrant
  serial: 1
  roles:
    - tutorial-common
    - tutorial-sdnip
    - tutorial-optical
    - tutorial-distributed