---
#
# Installs the GUI and does customizations, such as changing the background.
#
- name: Include vars
  hosts: localhost
  tasks:
  - include_vars: vars/global_vars.yml

- hosts: localhost
  remote_user: vagrant
  serial: 1
  roles:
    - gui
    - gui-customization