---
#
# Performs basic tasks to prepare the dev environment, such as managing the default user
# credentials, installing the basic packages, assigning host names.
#
- name: Setting password ubuntu and ssh key for user ubuntu
  user:
    name: ubuntu
    password: $6$rounds=656000$UcEQn7gcdsZCqt6m$HifWVYa6XXX5rpbAqkGj2mJfrIm9iT2AN2fbQbJNLcRr10SwhQgTQVnVqY8UGSQsD14WlFCdNCmJDay3CPlUR0
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  tags: [common]

- name: Installing basic packages
  apt:
    name: "{{ item }}"
    force: yes
  with_items: "{{ basic_packages }}"
  tags: [common]

- name: Installing python3-lxc
  pip:
    name: lxc-python2
    state: present
  tags: [common]